<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Tests\Controllers;

use SwaggerPetstoreOpenAPI30Lib\Controllers\UserController;
use SwaggerPetstoreOpenAPI30Lib\Exceptions;

class UserControllerTest extends BaseTestController
{
    /**
     * @var UserController UserController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getUserController();
    }

    public function testCreateUser()
    {
        // Parameters for the API call
        $id = 10;
        $username = 'theUser';
        $firstName = 'John';
        $lastName = 'James';
        $email = 'john@email.com';
        $password = '12345';
        $phone = '12345';
        $userStatus = 1;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createUser(
                $id,
                $username,
                $firstName,
                $lastName,
                $email,
                $password,
                $phone,
                $userStatus
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testCreateUser1()
    {
        // Parameters for the API call
        $id = 10;
        $username = 'theUser';
        $firstName = 'John';
        $lastName = 'James';
        $email = 'john@email.com';
        $password = '12345';
        $phone = '12345';
        $userStatus = 1;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createUser(
                $id,
                $username,
                $firstName,
                $lastName,
                $email,
                $password,
                $phone,
                $userStatus
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/xml', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testCreateUsersWithListInput()
    {
        // Parameters for the API call
        $body = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createUsersWithListInput($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testCreateUsersWithListInput1()
    {
        // Parameters for the API call
        $body = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createUsersWithListInput($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/xml', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testLoginUser1()
    {
        // Parameters for the API call
        $username = null;
        $password = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->loginUser($username, $password);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['X-Rate-Limit'] = ["", false];
        $headers['X-Expires-After'] = ["", false];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testLoginUser()
    {
        // Parameters for the API call
        $username = null;
        $password = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->loginUser($username, $password);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['X-Rate-Limit'] = ["", false];
        $headers['X-Expires-After'] = ["", false];
        $headers['Content-Type'] = ['application/xml', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testLogoutUser()
    {
        // Perform API call
        try {
            self::$controller->logoutUser();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
