<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Tests;

use Core\Types\CallbackCatcher;
use SwaggerPetstoreOpenAPI30Lib\Authentication\ApiKeyCredentialsBuilder;
use SwaggerPetstoreOpenAPI30Lib\Authentication\PetstoreAuthCredentialsBuilder;
use SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30Client;
use SwaggerPetstoreOpenAPI30Lib\SwaggerPetstoreOpenAPI30ClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): SwaggerPetstoreOpenAPI30Client
    {
        $clientBuilder = SwaggerPetstoreOpenAPI30ClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        SwaggerPetstoreOpenAPI30ClientBuilder $builder
    ): SwaggerPetstoreOpenAPI30ClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        SwaggerPetstoreOpenAPI30ClientBuilder $builder
    ): SwaggerPetstoreOpenAPI30ClientBuilder {
        $timeout = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_TIMEOUT');
        $numberOfRetries = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_ENVIRONMENT');
        $oAuthClientId = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_O_AUTH_CLIENT_ID');
        $oAuthRedirectUri = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_O_AUTH_REDIRECT_URI');
        $apiKey = getenv('SWAGGER_PETSTORE_OPEN_API_30_LIB_API_KEY');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($oAuthClientId) && !empty($oAuthRedirectUri)) {
            $builder->petstoreAuthCredentials(
                PetstoreAuthCredentialsBuilder::init($oAuthClientId, $oAuthRedirectUri)
            );
        }

        if (!empty($apiKey)) {
            $builder->apiKeyCredentials(ApiKeyCredentialsBuilder::init($apiKey));
        }

        return $builder;
    }
}
