<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing ApiKey security credentials.
 */
class ApiKeyCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for ApiKeyCredentialsBuilder
     *
     * @param string $apiKey
     */
    public static function init(string $apiKey): self
    {
        return new self(['apiKey' => $apiKey]);
    }

    /**
     * Setter for ApiKey.
     *
     * @param string $apiKey
     *
     * @return $this
     */
    public function apiKey(string $apiKey): self
    {
        $this->config['apiKey'] = $apiKey;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
