<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiKeyCredentials
{
    /**
     * String value for apiKey.
     */
    public function getApiKey(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apiKey
     */
    public function equals(string $apiKey): bool;
}
