<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Authentication;

use SwaggerPetstoreOpenAPI30Lib\Models\OAuthToken;

/**
 * Interface for defining the behavior of Authentication.
 */
interface PetstoreAuthCredentials
{
    /**
     * String value for oAuthClientId.
     */
    public function getOAuthClientId(): string;

    /**
     * String value for oAuthRedirectUri.
     */
    public function getOAuthRedirectUri(): string;

    /**
     * OAuthToken value for oAuthToken.
     */
    public function getOAuthToken(): ?OAuthToken;

    /**
     * OAuthScopePetstoreAuthEnum value for oAuthScopes.
     */
    public function getOAuthScopes(): ?array;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $oAuthClientId OAuth 2 Client ID
     * @param string $oAuthRedirectUri OAuth 2 Redirection endpoint or Callback Uri
     */
    public function equals(string $oAuthClientId, string $oAuthRedirectUri): bool;

    /**
     * Build an authorization URL for taking the user's consent to access data.
     *
     * @param string|null $state An opaque state string.
     * @param array|null $additionalParams Additional parameters to be sent.
     */
    public function buildAuthorizationUrl(?string $state = null, ?array $additionalParams = null): string;

    /**
     * Has the OAuth token expired? If the token argument is not provided then this function will check the
     * expiry of the initial oauthToken, that's set in the client initialization.
     */
    public function isTokenExpired(?OAuthToken $token = null): bool;
}
