<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Authentication;

use CoreInterfaces\Core\Request\RequestMethod;
use CoreInterfaces\Core\Request\TypeValidatorInterface;
use Core\Authentication\CoreAuth;
use Core\Client;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\AdditionalQueryParams;
use Core\Request\RequestBuilder;
use Core\Utils\CoreHelper;
use InvalidArgumentException;
use SwaggerPetstoreOpenAPI30Lib\Models\OAuthToken;
use SwaggerPetstoreOpenAPI30Lib\ConfigurationDefaults;

/**
 * Utility class for OAuth 2 authorization and token management
 */
class PetstoreAuthManager extends CoreAuth implements PetstoreAuthCredentials
{
    private $client;

    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        parent::__construct();
        $this->config = $config;
    }

    public function setClient(Client $client): void
    {
        $this->client = $client;
    }

    /**
     * String value for oAuthClientId.
     */
    public function getOAuthClientId(): string
    {
        return $this->config['oAuthClientId'] ?? ConfigurationDefaults::O_AUTH_CLIENT_ID;
    }

    /**
     * String value for oAuthRedirectUri.
     */
    public function getOAuthRedirectUri(): string
    {
        return $this->config['oAuthRedirectUri'] ?? ConfigurationDefaults::O_AUTH_REDIRECT_URI;
    }

    /**
     * OAuthToken value for oAuthToken.
     */
    public function getOAuthToken(): ?OAuthToken
    {
        $oAuthToken = $this->config['oAuthToken'];
        if ($oAuthToken instanceof OAuthToken) {
            return clone $oAuthToken;
        }
        return ConfigurationDefaults::O_AUTH_TOKEN;
    }

    /**
     * OAuthScopePetstoreAuthEnum value for oAuthScopes.
     */
    public function getOAuthScopes(): ?array
    {
        $oAuthScopes = $this->config['oAuthScopes'];
        if (is_array($oAuthScopes)) {
            return $oAuthScopes;
        }
        return ConfigurationDefaults::O_AUTH_SCOPES;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $oAuthClientId OAuth 2 Client ID
     * @param string $oAuthRedirectUri OAuth 2 Redirection endpoint or Callback Uri
     */
    public function equals(string $oAuthClientId, string $oAuthRedirectUri): bool
    {
        return $oAuthClientId == $this->getOAuthClientId() &&
            $oAuthRedirectUri == $this->getOAuthRedirectUri();
    }

    /**
     * Clock skew time in seconds applied while checking the OAuth Token expiry.
     */
    public function getOAuthClockSkew(): int
    {
        return $this->config['petstore_auth-ClockSkew'] ?? ConfigurationDefaults::PETSTORE_AUTH_CLOCK_SKEW;
    }

    /**
     * Build an authorization URL for taking the user's consent to access data.
     * @param  string|null       $state            An opaque state string
     * @param  array|null        $additionalParams Additional parameters to add the the authorization URL
     */
    public function buildAuthorizationUrl(?string $state = null, ?array $additionalParams = null): string
    {
        return (new RequestBuilder(RequestMethod::GET, ""))
            ->parameters(
                AdditionalQueryParams::init($additionalParams),
                AdditionalQueryParams::init([
                    'response_type' => 'code',
                    'client_id'     => $this->getOAuthClientId(),
                    'redirect_uri'  => $this->getOAuthRedirectUri(),
                    'scope'         => implode(' ', $this->getOAuthScopes() ?? []),
                    'state'         => $state
                ])
            )
            ->build($this->client)
            ->getQueryUrl();
    }

    /**
     * Has the OAuth token expired? If the token argument is not provided then this function will check the expiry of
     * the initial oauthToken, that's set in the client initialization.
     */
    public function isTokenExpired(?OAuthToken $token = null): bool
    {
        $token = $token ?? $this->getOAuthToken();
        if ($token == null || empty($token->getExpiry())) {
            return true;
        }
        return $token->getExpiry() < time() + $this->getOAuthClockSkew();
    }

    /**
     * Check if client is authorized, throws exceptions when token is null or expired.
     *
     * @throws InvalidArgumentException
     */
    public function validate(TypeValidatorInterface $validator): void
    {
        if ($this->getOAuthToken() == null) {
            throw new InvalidArgumentException('Client is not authorized. An OAuth token is needed to make API calls.');
        }
        if ($this->isTokenExpired()) {
            throw new InvalidArgumentException('OAuth token is expired. A valid token is needed to make API calls.');
        }
        parent::__construct(
            HeaderParam::init(
                'Authorization',
                CoreHelper::getBearerAuthString($this->getOAuthToken()->getAccessToken())
            )->requiredNonEmpty()
        );
        parent::validate($validator);
    }
}
