<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreOpenAPI30Lib\Models\ApiResponse;

/**
 * Builder for model ApiResponse
 *
 * @see ApiResponse
 */
class ApiResponseBuilder
{
    /**
     * @var ApiResponse
     */
    private $instance;

    private function __construct(ApiResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ApiResponse());
    }

    /**
     * Sets code field.
     *
     * @param int|null $value
     */
    public function code(?int $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Api Response object.
     */
    public function build(): ApiResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
