<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreOpenAPI30Lib\Models\Category;

/**
 * Builder for model Category
 *
 * @see Category
 */
class CategoryBuilder
{
    /**
     * @var Category
     */
    private $instance;

    private function __construct(Category $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Category Builder object.
     */
    public static function init(): self
    {
        return new self(new Category());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Category object.
     */
    public function build(): Category
    {
        return CoreHelper::clone($this->instance);
    }
}
