<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreOpenAPI30Lib\Models\OAuthToken;

/**
 * Builder for model OAuthToken
 *
 * @see OAuthToken
 */
class OAuthTokenBuilder
{
    /**
     * @var OAuthToken
     */
    private $instance;

    private function __construct(OAuthToken $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new O Auth Token Builder object.
     *
     * @param string $accessToken
     * @param string $tokenType
     */
    public static function init(string $accessToken, string $tokenType): self
    {
        return new self(new OAuthToken($accessToken, $tokenType));
    }

    /**
     * Sets expires in field.
     *
     * @param int|null $value
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets scope field.
     *
     * @param string|null $value
     */
    public function scope(?string $value): self
    {
        $this->instance->setScope($value);
        return $this;
    }

    /**
     * Sets expiry field.
     *
     * @param int|null $value
     */
    public function expiry(?int $value): self
    {
        $this->instance->setExpiry($value);
        return $this;
    }

    /**
     * Sets refresh token field.
     *
     * @param string|null $value
     */
    public function refreshToken(?string $value): self
    {
        $this->instance->setRefreshToken($value);
        return $this;
    }

    /**
     * Initializes a new O Auth Token object.
     */
    public function build(): OAuthToken
    {
        return CoreHelper::clone($this->instance);
    }
}
