<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreOpenAPI30Lib\Models\Order;

/**
 * Builder for model Order
 *
 * @see Order
 */
class OrderBuilder
{
    /**
     * @var Order
     */
    private $instance;

    private function __construct(Order $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Builder object.
     */
    public static function init(): self
    {
        return new self(new Order());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets pet Id field.
     *
     * @param int|null $value
     */
    public function petId(?int $value): self
    {
        $this->instance->setPetId($value);
        return $this;
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets ship Date field.
     *
     * @param \DateTime|null $value
     */
    public function shipDate(?\DateTime $value): self
    {
        $this->instance->setShipDate($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets complete field.
     *
     * @param bool|null $value
     */
    public function complete(?bool $value): self
    {
        $this->instance->setComplete($value);
        return $this;
    }

    /**
     * Initializes a new Order object.
     */
    public function build(): Order
    {
        return CoreHelper::clone($this->instance);
    }
}
