<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreOpenAPI30Lib\Models\Category;
use SwaggerPetstoreOpenAPI30Lib\Models\Pet;
use SwaggerPetstoreOpenAPI30Lib\Models\Tag;

/**
 * Builder for model Pet
 *
 * @see Pet
 */
class PetBuilder
{
    /**
     * @var Pet
     */
    private $instance;

    private function __construct(Pet $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pet Builder object.
     *
     * @param string $name
     * @param string[] $photoUrls
     */
    public static function init(string $name, array $photoUrls): self
    {
        return new self(new Pet($name, $photoUrls));
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets category field.
     *
     * @param Category|null $value
     */
    public function category(?Category $value): self
    {
        $this->instance->setCategory($value);
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param Tag[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Pet object.
     */
    public function build(): Pet
    {
        return CoreHelper::clone($this->instance);
    }
}
