<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Utils;

use Core\Types\Sdk\CoreFileWrapper;
use SwaggerPetstoreOpenAPI30Lib\ApiHelper;

/**
 * Wraps file with mime-type and filename to be sent as part of an HTTP request.
 */
class FileWrapper extends CoreFileWrapper
{
    /**
     * Create FileWrapper instance from a file on disk
     */
    public static function createFromPath(string $realFilePath, ?string $mimeType = null, ?string $filename = ''): self
    {
        return new self($realFilePath, $mimeType, $filename);
    }

    /**
     * Converts the FileWrapper object to a human-readable string representation.
     *
     * @return string The string representation of the FileWrapper object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('FileWrapper', [], parent::__toString());
    }
}
